name: "check"
on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main' }}

jobs:
  nix:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check nix flake
        run: nix flake check

      - name: Check nix formatting
        run: nix run nixpkgs#nixpkgs-fmt -- --check .

      - name: Build nix
        run: nix build .#darwinConfigurations."MacBook-Pro".system

  lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install selene
        run: |
          curl -sSL https://github.com/Kampfkarren/selene/releases/latest/download/selene-linux.zip -o selene.zip
          unzip selene.zip
          chmod +x selene
          sudo mv selene /usr/local/bin/

      - name: Install stylua
        run: |
          curl -sSL https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip -o stylua.zip
          unzip stylua.zip
          chmod +x stylua
          sudo mv stylua /usr/local/bin/

      - name: Lint lua
        run: selene config/nvim/lua

      - name: Check lua formatting
        run: stylua --check config/nvim/lua
