name: "check"
on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main' }}

jobs:
  nix:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check nix flake
        run: nix flake check

      - name: Build nix
        run: nix build .#darwinConfigurations."MacBook-Pro".system

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: extractions/setup-just@v2

      - uses: Kampfkarren/selene-action@v1
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check config/
      - uses: tamasfe/taplo-action@v0.4.2
        with:
          arguments: check
      - uses: crate-ci/typos@v1
      - uses: ludeeus/action-shellcheck@v2
        with:
          scandir: scripts
      - uses: raven-actions/actionlint@v2
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
