name: update-flake
on:
  schedule:
    - cron: '0 12 * * *' # Daily at 12pm UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeterminateSystems/update-flake-lock@v24
        with:
          pr-title: "flake.lock: weekly update"
          pr-labels: dependencies
